- name: deploy one petclinic to one server
  hosts: petclinic
  remote_user: ubuntu

  tasks:
  - name: copy the jar file to target host
    copy:
      src: /home/ubuntu/workspace/test/spring-petclinic-3.2.0-SNAPSHOT.jar
      dest: /home/ubuntu
  - name: run the jar file
    shell: nohup java -jar /home/ubuntu/spring-petclinic-3.2.0-SNAPSHOT.jar &
    args:
      executable: /bin/bash
