- name: deploy one petclinic to one server
  hosts: petclinic
  remote_user: jenkins

  tasks:
  - name: copy the jar file to target host
    copy:
      src: /home/wisccourant/jenkins/workspace/ans1/target/spring-petclinic-3.2.0-SNAPSHOT.jar
      dest: /home/jenkins
  - name: run the jar file
    shell: java -jar /home/jenkins/petclinic.jar &
    args:
      executable: /bin/bash
